import {
    FileText,
    FileSpreadsheet,
    ClipboardList,
    FileSignature,
    FileArchive,
    FileBox,
    NotebookPen,
} from 'lucide-react';
import { DocumentType } from '@/types/documents';

export const DOCUMENT_TYPES: DocumentType[] = [
    {
        id: 'booking',
        name: 'Booking PDF',
        description: 'Reservas confirmadas con la naviera.',
        formats: ['PDF'],
        icon: FileSpreadsheet,
        accent: 'text-cyan-300',
        gradient: 'from-cyan-500/15 to-slate-900/60',
    },
    {
        id: 'factura-proforma',
        name: 'Factura Proforma',
        description: 'Cotizaciones previas a la factura comercial.',
        formats: ['PDF', 'XLSX'],
        icon: FileSignature,
        accent: 'text-sky-300',
        gradient: 'from-sky-500/15 to-slate-900/60',
    },
    {
        id: 'instructivo-embarque',
        name: 'Instructivo de Embarque',
        description: 'Indicaciones para navieras y transporte.',
        formats: ['PDF', 'XLSX'],
        icon: ClipboardList,
        accent: 'text-emerald-300',
        gradient: 'from-emerald-500/15 to-slate-900/60',
    },
    {
        id: 'packing-list',
        name: 'Packing List',
        description: 'Contenido detallado del embarque.',
        formats: ['PDF', 'XLSX'],
        icon: FileBox,
        accent: 'text-amber-300',
        gradient: 'from-amber-500/15 to-slate-900/60',
    },
    {
        id: 'guia-despacho',
        name: 'Guía de Despacho',
        description: 'Documentos de traslado nacional.',
        formats: ['PDF'],
        icon: NotebookPen,
        accent: 'text-indigo-300',
        gradient: 'from-indigo-500/15 to-slate-900/60',
    },
    {
        id: 'documentos-aga',
        name: 'Documentos AGA',
        description: 'Libera mercancía ante Aduanas y SAG.',
        formats: ['PDF'],
        icon: FileArchive,
        accent: 'text-fuchsia-300',
        gradient: 'from-fuchsia-500/15 to-slate-900/60',
    },
    {
        id: 'bl',
        name: 'BL / MBL / HBL',
        description: 'Conocimientos de embarque firmados.',
        formats: ['PDF'],
        icon: FileText,
        accent: 'text-rose-300',
        gradient: 'from-rose-500/15 to-slate-900/60',
    },
    {
        id: 'cert-origen',
        name: 'Cert. Origen',
        description: 'Certificado de origen de la mercancía.',
        formats: ['PDF'],
        icon: FileText,
        accent: 'text-violet-300',
        gradient: 'from-violet-500/15 to-slate-900/60',
    },
    {
        id: 'cert-fito',
        name: 'Cert Fito',
        description: 'Certificado fitosanitario.',
        formats: ['PDF'],
        icon: FileText,
        accent: 'text-teal-300',
        gradient: 'from-teal-500/15 to-slate-900/60',
    },
];
