@echo off
echo Iniciando ASLI Gestión Logística...
cd /d "C:\Users\Rodrigo Caceres\Desktop\CODE DEVELOPER\ASLI SUPABASE"
echo Limpiando cache...
if exist .next rmdir /s /q .next
echo Instalando dependencias...
npm install
echo Iniciando servidor de desarrollo...
npm run dev
pause

